src/app/api/server/[...path]/route.ts
=> fix: route handler RouteContext 사용

src/app/api/server/[...path]/route.ts
=> 파라미터로 NextRequest만 받게 수정

.gitattributes, public/video/promotion.mp4, public/video/promotion.webm, src/shared/ui/Header/index.tsx, src/shared/utils/scroll.ts, src/views/home/ui/HomePage/index.tsx, src/views/home/ui/SloganMarquee/index.tsx, src/widgets/main/ui/video/index.tsx, tailwind.config.ts
홍보 영상 화면, 슬로건 메인페이지 제작
교육청 테스트 확인을 위해 코드정리가 안된 상태인데 pr 올립니다!
영상 크기가 커서 Git LFS 사용해서 올렸습니다
=> feat: 메인페이지 일부 제작

src/app/layout.tsx, src/shared/ui/ChannelTalk/index.tsx
=> feat: 채널톡 추가

src/app/test/home/page.tsx, src/middleware.ts, src/shared/ui/Header/index.tsx, src/views/home/ui/HomePage/index.tsx
메인화면 구현사항 파악하실 수 있도록 경로 추가
/test/home url로 메인 페이지 접근 가능하게
나머지 경로는 모두 /home으로 이동
=> feat: 테스트 페이지

src/entities/slogan/ui/Agree/index.tsx, src/entities/slogan/ui/Check/index.tsx, src/entities/slogan/ui/Danger/index.tsx, src/views/slogan/ui/SloganPage/index.tsx, src/widgets/slogan/ui/Modal/index.tsx
> 동의 비동의 모달을 추가 했습니다
> 동의 문구가 맞는지 잘 확인해주세요 ㅠㅠ
=> feat: 동의 비동의 모달 추가

public/video/video1.mp4, public/video/video1.webm, public/video/video2.mp4, public/video/video2.webm, src/entities/home/ui/Video/index.tsx
메인 비디오 영상을 두개로 분리
메인 비디오 파일 .mp4, .wepm이 기존 100mb 이상으로 깃허브에 업로드가 안됐었는데
영상을 두개로 분리, 코드로 연결해 사용하여 해결하였습니다
=> fest:메인 비디오 수정

src/widgets/main/ParticipationThirdSection/index.tsx
=> hotfix: 섹션 제목이 잘리는 문제 해결 

src/views/apply/ui/ApplyPage/index.tsx, src/widgets/main/SloganSecondSection/index.tsx
=> feat: 안내사항을 추가했습니다

src/shared/ui/Header/index.tsx, src/widgets/main/PreliminaryFourthSection/index.tsx, src/widgets/main/ReservationFifthSection/index.tsx, src/widgets/main/SloganSecondSection/index.tsx
- 텍스트 수정 (본선 예매 -> 본선 좌석예매)
- 예선 섹션 디자인 변경
- 슬로건 등수 표시 가로 1열로 변경
=> Feat: 디자인 변경 요구사항 반영 

src/entities/evaluation/api/saveScore.ts, src/entities/evaluation/ui/EvaluationCard/index.tsx, src/entities/evaluation/ui/Standard/index.tsx, src/views/evaluation/api/getEvaluation.ts, src/views/evaluation/api/getEvaluations.ts, src/views/evaluation/model/score.ts, src/views/evaluation/model/useGetEvaluation.ts, src/views/evaluation/model/useGetEvaluations.ts, src/views/evaluation/ui/EvaluationView/index.tsx
> 심사 페이지 변경 사항을 반영했습니다
- 확인 버튼 제거
- 저장 로직 추가
- 심사 조회 로직 추가
=> fix: 심사 페이지 변경 사항을 반영

src/shared/config/authConfig.ts
=> chore: temp

src/widgets/main/ReservationFifthSection/index.tsx
=> Fix: formatDataLeft 함수 로직을 견고하게 수정했습니다

src/widgets/main/ReservationFifthSection/index.tsx
=> Add: 티켓 수령 안내 코멘트 추가

src/entities/rank/ui/TopRank/index.tsx, src/views/rank/ui/RankView/index.tsx
=> fix: rank 페이지 요구사항 반영

src/views/home/ui/HomePage/index.tsx
> 해당 PR의 변경사항, 해당 이슈 등에 대한 간략한 설명을 작성해주세요.
- {변경사항}
> 해당 PR에서 작업한 내용을 자세히 설명해주세요. + 스크린 샷샷
> 리뷰어분들이 리뷰를 할 때 참고하면 좋을 사항이나 질문사항을 작성해주세요.
> 구현 중 고민이나 특정 부분에 대한 설명 등을 작성하면 좋습니다.
> e.g. 이 부분은 이렇게 구현했는데, 이게 맞는 방향인지 궁금합니다.
작성하지 않은 부분은 삭제해주세요.
=> feat: 점검 모달

src/views/home/ui/HomePage/index.tsx, src/widgets/main/FinalsSixthSection/index.tsx
길찾기 비디오 유튜브로 변경 하였습니다.
footer는 완성까지 임시 주석처리 시켰습니다
=> Fix:video 유튜브 변경 및 footer 임시 주석처리

src/entities/booking/lib/useMySeat.ts, src/entities/booking/ui/BookingInfoDisplay/index.tsx, src/entities/booking/ui/SeatGrid/index.tsx, src/middleware.ts, src/shared/config/authConfig.ts, src/shared/ui/Header/index.tsx, src/views/booking/ui/BookingPage/index.tsx, src/views/booking/ui/MyBookingPage/index.tsx, src/widgets/booking/lib/usePerformerSeatSelection.ts, src/widgets/booking/ui/SeatSection/index.tsx, src/widgets/main/ReservationFifthSection/index.tsx, src/widgets/signin/lib/handleLogout.ts
=> Fix: myseat router

src/views/list/api/getTeams.ts, src/views/score/ui/scoreView/index.tsx
- /team 404 해결
- score 페이지에서 팀명 표시
=> Fix: vote api

src/views/vote/ui/VoteView/index.tsx
> #132 
- {변경사항}
> 해당 PR에서 작업한 내용을 자세히 설명해주세요. + 스크린 샷샷
> 리뷰어분들이 리뷰를 할 때 참고하면 좋을 사항이나 질문사항을 작성해주세요.
> 구현 중 고민이나 특정 부분에 대한 설명 등을 작성하면 좋습니다.
> e.g. 이 부분은 이렇게 구현했는데, 이게 맞는 방향인지 궁금합니다.
작성하지 않은 부분은 삭제해주세요.
=> fix: default value

src/views/list/ui/ListView/index.tsx, src/widgets/list/ui/TeamSlide/index.tsx
=> fix: list length

src/entities/booking/model/lotterySeats.ts
=> feat: 좌석 데이터 추가
